"""Add swing_num to analysis and file tables

Revision ID: 1aeeb2e628a5
Revises: b37b365a036a
Create Date: 2026-02-22 19:05:12.865851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aeeb2e628a5'
down_revision: Union[str, Sequence[str], None] = 'b37b365a036a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('swing_num', sa.Integer(), nullable=True))
    op.add_column('file', sa.Column('swing_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'swing_num')
    op.drop_column('analysis', 'swing_num')
    # ### end Alembic commands ###
